spring.application.name=teleprompter



spring.datasource.url=jdbc:postgresql://localhost:5432/teleprompter_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Force UTC if you prefer consistency
# spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata';
